[package]
name = "pk"
version = "0.1.0"
authors = ["ruby <lqy@x87.org>"]
edition = "2018"

[dependencies]
# Hyper is an asynchronous HTTP library. We'll use it to power our HTTP
# server and to make HTTP requests.
hyper = "0.13"
# To setup some sort of runtime needed by Hyper, we will use the Tokio runtime.
tokio = { version = "0.2", features = ["full"] }

# (only for testing)
reqwest = { version = "0.10.4", features = ["blocking", "socks"] }

log = "0.4"
env_logger = "0.7.1"
httparse = "1.3.4"
async-socks5 = "0.3.1"
tokio-socks = "0.2.0" # come onto GH earlier than async-socks5
socks = "0.3.2"
futures = "0.3.5"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
#[dependencies]
#rocket = "0.4.5"
#serde = "1.0"
#serde-pickle = "0.6"
#
#[dependencies.rocket_contrib]
#version = "0.4.5"
#default-features = false
#features = ["handlebars_templates", "tera_templates"]
#
#[dependencies.redis]
#version = "*"
#
#[dependencies]
#rcin = "0.2.1"

#[dependencies]
#itertools = "0.9.0"
#ndarray = "0.13.1"
